/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import clusters.DynamicWeakGaussianAffinityMatrix;
import files.DocumentDictionary;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import tfidf.TfidfVectorSpaceDocumentRepresentation;

/**
 *
 * @author doried
 */
public class LinkDetectionGui extends javax.swing.JFrame {

    private DynamicWeakGaussianAffinityMatrix affinity ;
    private List<TfidfVectorSpaceDocumentRepresentation> docs;
    private DocumentDictionary docDic;
    /**
     * Creates new form LinkDetectionGui
     */
    public LinkDetectionGui(DynamicWeakGaussianAffinityMatrix affinity,DocumentDictionary docDic) {
        initComponents();
        this.affinity = affinity;
        this.docs = affinity.getAllDocs();
        this.docDic = docDic;
        cboFirstStory.removeAllItems();
        cboSecondStory.removeAllItems();
        for(TfidfVectorSpaceDocumentRepresentation doc : docs){
            cboFirstStory.addItem(doc);
            cboSecondStory.addItem(doc);
        }
        cboFirstStory.addItemListener(new ItemListener() {

            @Override
            public void itemStateChanged(ItemEvent e) {
                try{
                    TfidfVectorSpaceDocumentRepresentation selected = (TfidfVectorSpaceDocumentRepresentation) cboFirstStory.getSelectedItem();
                    txtStory1.setText(docDic.getStoryFileByUrl(
                            selected.getStoryFile().getStoryUrl()
                    ).getStoryContent());
                    computeSimilarity();
                }catch(Exception ee)
                {
                    System.err.println(ee.toString());
                }
            }
        });
        cboSecondStory.addItemListener(new ItemListener() {

            @Override
            public void itemStateChanged(ItemEvent e) {
                try{
                    TfidfVectorSpaceDocumentRepresentation selected = (TfidfVectorSpaceDocumentRepresentation) cboSecondStory.getSelectedItem();
                    txtStory2.setText(docDic.getStoryFileByUrl(
                            selected.getStoryFile().getStoryUrl()
                    ).getStoryContent());
                    computeSimilarity();
                }catch(Exception ee){
                    System.err.println(ee.toString());
                }
            }
        });
    }

    public void computeSimilarity(){
        try{
            TfidfVectorSpaceDocumentRepresentation story1 = (TfidfVectorSpaceDocumentRepresentation) cboFirstStory.getSelectedItem();
            TfidfVectorSpaceDocumentRepresentation story2 = (TfidfVectorSpaceDocumentRepresentation) cboSecondStory.getSelectedItem();
            double similarity = affinity.getAffinity(story1.getIndex(), story2.getIndex());
            double cosineSim = affinity.getSimilarity(story1.getIndex(), story2.getIndex());
            txtResult.setText(similarity + "");
            txtCosineSimilarity.setText(cosineSim + "");
        }
        catch(Exception ee){}
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboFirstStory = new javax.swing.JComboBox();
        cboSecondStory = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtResult = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtStory1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtStory2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtCosineSimilarity = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cboFirstStory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboSecondStory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("First Story");

        jLabel2.setText("Second Story");

        jLabel3.setText("Scaled Similarity is ");

        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 0, 2));

        txtStory1.setColumns(20);
        txtStory1.setLineWrap(true);
        txtStory1.setRows(5);
        jScrollPane1.setViewportView(txtStory1);

        jPanel1.add(jScrollPane1);

        txtStory2.setColumns(20);
        txtStory2.setLineWrap(true);
        txtStory2.setRows(5);
        jScrollPane2.setViewportView(txtStory2);

        jPanel1.add(jScrollPane2);

        jLabel4.setText("Cosine Similarity is ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel2)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboFirstStory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboSecondStory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtResult))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCosineSimilarity)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboFirstStory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboSecondStory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCosineSimilarity, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel3.getAccessibleContext().setAccessibleDescription("Scaled Similarity is ");

        getAccessibleContext().setAccessibleName("Link Detection Task");

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboFirstStory;
    private javax.swing.JComboBox cboSecondStory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtCosineSimilarity;
    private javax.swing.JTextField txtResult;
    private javax.swing.JTextArea txtStory1;
    private javax.swing.JTextArea txtStory2;
    // End of variables declaration//GEN-END:variables
}
