/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import clusters.DynamicWeakGaussianAffinityMatrix;
import files.DocumentDictionary;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import tfidf.IdfExternalProvider;
import tfidf.TfidfVectorSpaceDocumentRepresentation;
import work.TDTJava;

/**
 *
 * @author doried
 */
public class MainGui extends javax.swing.JFrame {

    /**
     * Creates new form MainGui
     */
    public MainGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTestLinkDetection = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTestTopicTracking = new javax.swing.JButton();
        btnTestFSD = new javax.swing.JButton();
        btnTestTopicDetection = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnTestLinkDetection.setText("Test Link Detection");
        btnTestLinkDetection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestLinkDetectionActionPerformed(evt);
            }
        });

        jLabel1.setText("Topic Detection And Tracking System");

        btnTestTopicTracking.setText("Test Topic Tracking");
        btnTestTopicTracking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestTopicTrackingActionPerformed(evt);
            }
        });

        btnTestFSD.setText("Test First Story Detection");
        btnTestFSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestFSDActionPerformed(evt);
            }
        });

        btnTestTopicDetection.setText("Test Topic Detection");
        btnTestTopicDetection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestTopicDetectionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTestTopicTracking, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTestLinkDetection, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTestFSD, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTestTopicDetection, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnTestLinkDetection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTestTopicTracking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTestFSD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTestTopicDetection)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Topic Detection and Tracking System");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTestLinkDetectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestLinkDetectionActionPerformed
        DynamicWeakGaussianAffinityMatrix aff;
        try {
            aff = TDTJava.getAffinityMatrixForEvaluation();
            DocumentDictionary docDic = TDTJava.getDocumentDictionary();
            JFrame frame = new LinkDetectionGui(aff,docDic);
            frame.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainGui.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_btnTestLinkDetectionActionPerformed

    private void btnTestTopicTrackingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestTopicTrackingActionPerformed
        try {
            List<TfidfVectorSpaceDocumentRepresentation> docs = TDTJava.getDocumentsForEvaluation();
            DocumentDictionary docDic = TDTJava.getDocumentDictionary();
            JFrame frame = new TopicTrackingGui(docs, docDic, (IdfExternalProvider) docs.get(0).getIdfProvider());
            frame.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTestTopicTrackingActionPerformed

    private void btnTestTopicDetectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestTopicDetectionActionPerformed
        try {
            new TopicDetection(work.TDTJava.getTopicDetectionResults());
        } catch (Exception ex) {
            System.err.println(ex.toString());
        }
    }//GEN-LAST:event_btnTestTopicDetectionActionPerformed

    private void btnTestFSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestFSDActionPerformed
         try {
            new FSD(work.TDTJava.getFSDResults());
        } catch (Exception ex) {
           ex.printStackTrace();
        }
    }//GEN-LAST:event_btnTestFSDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTestFSD;
    private javax.swing.JButton btnTestLinkDetection;
    private javax.swing.JButton btnTestTopicDetection;
    private javax.swing.JButton btnTestTopicTracking;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
